services:
  - type: web
    name: trl-compas-dashboard
    runtime: static
    staticPublishPath: ./dashboard
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
